name: 'dw_local_free'
version: '1.0.0'
config-version: 2

profile: 'dw_local_free'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dw_local_free:
    +materialized: table
    mart:
      +materialized: materialized_view
      +unique_key: "observation_date || '_' || location_name"

seeds:
  dw_local_free:
    +quote_columns: false

